# Label definitions for bug tracking and project management
- name: "bug"
  description: "Something isn't working as expected."
  color: "d73a4a"
- name: "enhancement"
  description: "A new feature or request."
  color: "a2eeef"
- name: "question"
  description: "Further information is requested."
  color: "d876e3"
- name: "documentation"
  description: "Improvements or additions to documentation."
  color: "0075ca"
- name: "status: available"
  description: "This issue is open and ready to be worked on."
  color: "ffffff"
- name: "status: in-progress"
  description: "This issue is currently being worked on."
  color: "fef2c0"
- name: "status: blocked"
  description: "This issue cannot be worked on until a dependency is resolved."
  color: "e5a753"
- name: "priority: critical"
  description: "This must be addressed immediately."
  color: "b60205"
- name: "priority: high"
  description: "High-priority issue."
  color: "d93f0b"
- name: "priority: medium"
  description: "Medium-priority issue."
  color: "fbca04"
- name: "priority: low"
  description: "Low-priority issue."
  color: "0e8a16"
