import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://stage.tripleten.percruit.com/');
  await page.getByRole('textbox', { name: 'user@example.com' }).click();
  await page.getByRole('textbox', { name: 'user@example.com' }).fill('joshuabennett353+student@gmail.comjoshuabennett353+student@gmail.com');
  await page.getByRole('textbox', { name: 'user@example.com' }).click();
  await page.getByRole('textbox', { name: 'user@example.com' }).click();
  await page.getByRole('textbox', { name: 'user@example.com' }).click();
  await page.getByRole('textbox', { name: 'user@example.com' }).dblclick();
  await page.getByRole('textbox', { name: 'user@example.com' }).fill('joshuabennett353+student@gmail.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('AuDY6wz9X9eiHdt');
  await page.getByRole('button', { name: 'toggle password visibility' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Accept all cookies' }).click();
  await page.getByRole('link', { name: 'Content Builder' }).click();
  await page.getByRole('tab', { name: 'Create New' }).click();
  await page.getByRole('button', { name: 'Recruiter Email Cold outreach' }).click();
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).click();
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).fill('google recruiter');
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).press('Tab');
  await page.getByRole('textbox', { name: 'Subject Line' }).fill('test');
  await page.getByRole('textbox', { name: 'Subject Line' }).press('Tab');
  await page.getByRole('textbox', { name: 'Message Content' }).fill('generated');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Yes, I sent it' }).click();
  await page.getByRole('button', { name: 'Follow-up Email After' }).click();
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).click();
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).fill('follow up email 3/33');
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).press('Tab');
  await page.getByRole('textbox', { name: 'Subject Line' }).fill('ddddd');
  await page.getByRole('textbox', { name: 'Message Content' }).click();
  await page.getByRole('textbox', { name: 'Message Content' }).fill('dfffjkkl;;;kdjfkdjfjdfdfjjdjdjjfdjfjdfjjdncnn');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Yes, I sent it' }).click();
  await page.getByRole('button', { name: 'Thank You Letter Post-' }).click();
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).click();
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).fill('thank you');
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).press('Tab');
  await page.getByRole('textbox', { name: 'Subject Line' }).fill('dddd');
  await page.getByRole('textbox', { name: 'Message Content' }).click();
  await page.getByRole('textbox', { name: 'Message Content' }).fill('testing again');
  await page.getByRole('button', { name: 'Generate with AI' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Yes, I sent it' }).click();
  await page.getByRole('button', { name: 'Networking Email Build' }).click();
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).click();
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).fill('this is my test again');
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).press('Tab');
  await page.getByRole('textbox', { name: 'Subject Line' }).fill('testinggggggg');
  await page.getByRole('textbox', { name: 'Subject Line' }).press('Tab');
  await page.getByRole('textbox', { name: 'Message Content' }).fill('here we go');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Yes, I sent it' }).click();
  await page.getByRole('button', { name: 'LinkedIn Connection Short' }).click();
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).click();
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).fill('linkedin testing continues');
  await page.getByRole('textbox', { name: 'Message Content' }).click();
  await page.getByRole('textbox', { name: 'Message Content' }).fill('wjat dpes tjos ,eam ;e\nts fomd pit/');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Not yet' }).click();
  await page.getByRole('button', { name: 'LinkedIn InMail Professional' }).click();
  await page.getByRole('button', { name: 'Generate with AI' }).click();
  await page.getByRole('button', { name: 'Copy to clipboard' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Yes, I sent it' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('button', { name: '📄 My Resumes' }).click();
  await page.getByRole('button', { name: '✨ AI-Tailored' }).click();
  await page.getByRole('button', { name: 'Open' }).first().click();
  await page.getByText('No AI-generated resumes yet').click();
  await page.locator('div').filter({ hasText: /^Context \(Optional\)1 selected$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Context \(Optional\)1 selected$/ }).first().click();
  await page.getByRole('button', { name: 'From Network Tracker' }).click();
  await page.getByRole('button', { name: '📋 From Job Tracker' }).click();
  await page.getByRole('button', { name: '✏️ Manual Entry' }).click();
  await page.getByRole('textbox', { name: 'Company Name' }).click();
  await page.getByRole('textbox', { name: 'Company Name' }).fill('subway');
  await page.getByRole('textbox', { name: 'Company Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Job Title' }).press('Tab');
  await page.getByRole('textbox', { name: 'Job Title' }).click();
  await page.getByRole('textbox', { name: 'Job Title' }).fill('paris baguette');
  await page.getByRole('textbox', { name: 'Recruiter Name (Optional)' }).click();
  await page.getByRole('textbox', { name: 'Recruiter Name (Optional)' }).fill('idk');
  await page.locator('.MuiBox-root.css-1fjtzvx').click();
  await page.getByText('Resume📄 My Resumes✨ AI-TailoredSelect AI ResumeSelect AI ResumeJob📋 From Job').click();
  await page.locator('.MuiBox-root.css-g6clnt > .MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root').click();
  await page.getByText('No contacts in your network').click();
  await page.locator('div').filter({ hasText: /^Recipient$/ }).click();
  await page.getByRole('spinbutton', { name: 'Max Character Count (optional)' }).click();
  await page.getByRole('textbox', { name: 'Additional Instructions (' }).click();
  await page.getByRole('textbox', { name: 'Additional Instructions (' }).fill('ff');
  await page.getByRole('spinbutton', { name: 'Max Character Count (optional)' }).click();
  await page.getByRole('spinbutton', { name: 'Max Character Count (optional)' }).fill('3333');
  await page.locator('.MuiBox-root.css-1fjtzvx').click();
  await page.getByRole('tab', { name: 'Saved' }).click();
  await page.getByText('LinkedIn InMail').nth(1).click();
  await page.getByText('LinkedIn InMail - Mar').click();
  await page.getByRole('row', { name: 'LinkedIn InMail - Mar 13 Hi [' }).getByLabel('Click to change status').click();
  await page.getByRole('row', { name: 'LinkedIn InMail - Mar 13 Hi [' }).getByLabel('Copy content').click();
  await page.getByRole('row', { name: 'LinkedIn InMail - Mar 13 Hi [' }).getByLabel('View details').click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('textbox', { name: 'Message Content' }).click();
  await page.getByRole('textbox', { name: 'Message Content' }).fill('Hi [Hiring Manager Name],\n\nI’ve been following [Company Name]’s recent work in the [Industry] space, and I was particularly impressed by your team\'s commitment to delivering seamless user experiences. With my unique background as an Emmy Award-winning producer turned QA Eddddngineer, I am eager to bring a high-level eye for detail and technical precision to your quality assurance team.\n\nThroughout my 6+ years of experience, I have developed a "pixel-perfect" mindset. At WHDH-TV, I managed high-pressure broadcast environments where accuracy and brand consistency were non-negotiable. I have since transitioned those editorial skills into the technical domain, specializing in automated and manual testing for digital experiences.\n\nMy core technical strengths include:\n- Developing robust automation frameworks using React, Selenium, and the Page Object Model (POM).\n- Managing defect lifecycles and cross-functional workflows via JIRA and Figma.\n- Ensuring multimedia and streaming asset integrity across various platforms, including Android Emulators.\n- A deep understanding of the creative vision, ensuring that technical performance never compromises design or editorial clarity.\n\nI am confident that my blend of technical QA expertise and creative production experience would make me a versatile asset to your engineering team. \n\nAre you open to a brief conversation next Tuesday or Wednesday to discuss how my background aligns with your current quality goals? I’d love to learn more about the challenges your team is currently tackling.\n\nBest regards,\n\nJoshua Bennett\nJoshuaBennett353@gmail.com\n860-610-8486');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Yes, I sent it' }).click();
  await page.getByRole('tab', { name: 'Saved' }).click();
  await page.getByRole('row', { name: 'LinkedIn InMail - Mar 13 Hi [Hiring Manager Name], I’ve been following [Company Name... LinkedIn InMail Click to change status - 3/13/2026 Mark as sent View details Copy content Delete', exact: true }).getByLabel('Mark as sent').click();
  await page.getByRole('row', { name: 'linkedin testing continues' }).getByLabel('Mark as sent').click();
  await page.getByRole('row', { name: 'LinkedIn InMail - Mar 13 Hi [Hiring Manager Name], I’ve been following [Company Name... LinkedIn InMail Click to change status subway 3/13/2026 View details Copy content Delete', exact: true }).getByLabel('Delete').click();
  await page.getByRole('row', { name: 'google recruiter generated' }).getByLabel('Delete').click();
  await page.getByRole('row', { name: 'thank you Dear Hiring Manager' }).getByLabel('Copy content').click();
  await page.getByRole('tab', { name: 'Create New' }).click();
});