import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://stage.tripleten.percruit.com/');
  await page.getByRole('textbox', { name: 'user@example.com' }).click();
  await page.getByRole('textbox', { name: 'user@example.com' }).fill('joshuabennett353+student@gmail.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('joshuabennett353+student@gmail.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).dblclick();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('AuDY6wz9X9eiHdt');
  await page.getByRole('button', { name: 'toggle password visibility' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Content Builder' }).click();
  await page.getByRole('tab', { name: 'Saved' }).click();
  await page.getByRole('row', { name: 'linkedin testing continues' }).getByLabel('Delete').click();
  await page.getByRole('row', { name: 'LinkedIn InMail - Mar 18 Hi' }).getByLabel('View details').click();
  await page.getByText('×').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('row', { name: 'LinkedIn InMail - Mar 17 Hi' }).getByLabel('Copy content').click();
  await page.getByRole('row', { name: 'google recruiter generated... Recruiter Email Click to change status - 3/16/2026 Mark as sent View details Copy content Delete', exact: true }).getByLabel('Mark as sent').click();
  await page.locator('tr:nth-child(7) > .MuiTableCell-root.MuiTableCell-body.MuiTableCell-alignRight > .MuiBox-root > .MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeSmall.css-1lmus55').click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('textbox', { name: 'Message Content' }).click();
  await page.getByRole('textbox', { name: 'Message Content' }).fill('generated joddijfjdnndsd');
  await page.getByRole('textbox', { name: 'Subject Line' }).click();
  await page.getByRole('textbox', { name: 'Subject Line' }).fill('test cddfadf');
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).click();
  await page.getByRole('textbox', { name: 'Subject Line' }).fill('test cddfadf ');
  await page.getByRole('textbox', { name: 'Title (for your reference)' }).fill('google recruiterdddd');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Not yet' }).click();
  await page.getByRole('tab', { name: 'Saved' }).click();
  await page.locator('tr:nth-child(10) > .MuiTableCell-root.MuiTableCell-body.MuiTableCell-alignRight > .MuiBox-root > .MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeSmall.css-1lmus55').click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('textbox', { name: 'Message Content' }).click();
  await page.getByRole('textbox', { name: 'Message Content' }).fill('testing again ddddff');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Not yet' }).click();
  await page.getByRole('button', { name: 'Not yet' }).click();
});