import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://stage.tripleten.percruit.com/');
  await page.getByRole('textbox', { name: 'user@example.com' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('1Passw0rd!');
  await page.getByRole('textbox', { name: 'user@example.com' }).click();
  await page.getByRole('textbox', { name: 'user@example.com' }).fill('qa+100119@qaexternship.testinator.com');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Coding Problems' }).click();
  await page.getByRole('button', { name: 'Coding Problems' }).click();
  await page.getByRole('button', { name: '×' }).click();
  await page.getByRole('tab', { name: 'Activities' }).click();
  await page.getByRole('combobox').first().click();
  await page.getByRole('option', { name: 'Test' }).click();
  await page.getByRole('combobox').nth(1).click();
  await page.getByRole('option', { name: 'Ultramarine' }).click();
  await page.getByRole('combobox').nth(2).click();
  await page.getByRole('option', { name: 'The Warp' }).click();
  await page.getByRole('button', { name: 'Add Activity' }).click();
  await page.getByRole('tab', { name: 'Basic Info' }).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill('Testing');
  await page.getByRole('textbox', { name: 'Title' }).press('Tab');
  await page.getByRole('textbox', { name: 'Description' }).fill('Tester');
  await page.getByRole('button', { name: 'Create Problem' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).dblclick();
  await page.getByRole('textbox', { name: 'Title' }).fill('Warhammer');
  await page.getByRole('textbox', { name: 'Title' }).press('Tab');
  await page.getByRole('textbox', { name: 'Description' }).fill('In the grimdark future of 40,000');
  await page.getByRole('button', { name: 'Update Problem' }).click();
  await page.getByRole('tab', { name: 'Categories' }).click();
  await page.locator('div').filter({ hasText: /^TestTest$/ }).first().click();
  await page.getByText('Topics').nth(4).click();
  await page.locator('div:nth-child(4) > .MuiPaper-root > .MuiCardContent-root > .MuiBox-root.css-lhftxy > div:nth-child(2) > button').first().click();
  await page.getByRole('button', { name: 'Cancel' }).click();
});