import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.getByRole('button', { name: 'Coding Problems' }).click();
  await page.getByRole('button', { name: 'Add Category' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('Test');
  await page.locator('div').filter({ hasText: /^Description$/ }).click();
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Test');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('tab', { name: 'Activities' }).click();
  await page.getByRole('combobox').first().click();
  await page.getByRole('option', { name: 'Test' }).click();
  await page.getByRole('combobox').nth(1).click();
  await page.locator('.MuiBackdrop-root.MuiBackdrop-invisible').click();
  await page.getByRole('combobox').nth(2).click();
  await page.getByRole('combobox').nth(2).click();
  await page.getByRole('tab', { name: 'Topics' }).click();
  await page.getByRole('button', { name: 'Add Topic' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('Test');
  await page.locator('div').filter({ hasText: /^Description$/ }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Test');
  await page.getByRole('textbox', { name: 'Description' }).press('F12');
  await page.getByRole('textbox', { name: 'Description' }).fill('Test');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('tab', { name: 'Units' }).click();
  await page.getByRole('combobox').nth(1).click();
  await page.getByRole('option', { name: 'Test' }).click();
  await page.getByRole('button', { name: 'Add Unit' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('Test');
  await page.locator('div').filter({ hasText: /^Description$/ }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Test');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('tab', { name: 'Activities' }).click();
  await page.getByRole('combobox').nth(2).click();
  await page.getByRole('option', { name: 'Test' }).click();
  await page.getByRole('button', { name: 'Add Activity' }).click();
  await page.getByRole('tab', { name: 'Basic Info' }).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill('test');
  await page.getByRole('textbox', { name: 'Title' }).press('Tab');
  await page.getByRole('textbox', { name: 'Description' }).fill('test');
  await page.getByRole('button', { name: 'Create Problem' }).click();
});