import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://stage.tripleten.percruit.com/');
  await page.getByRole('textbox', { name: 'user@example.com' }).click();
  await page.getByRole('textbox', { name: 'user@example.com' }).fill('cheyannejaileen16+admin@gmail.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Externship22');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Mentors' }).click();
  await page.getByRole('textbox', { name: 'Search mentors by name, email' }).click();
  await page.getByRole('textbox', { name: 'Search mentors by name, email' }).fill('Cheyanne Darby');
  await page.getByRole('heading', { name: 'Cheyanne Darby' }).click();
  await page.getByRole('heading', { name: 'Mentors (1)' }).click();
  await page.getByRole('textbox', { name: 'Search mentors by name, email' }).click();
  await page.getByRole('textbox', { name: 'Search mentors by name, email' }).click();
  await page.getByRole('textbox', { name: 'Search mentors by name, email' }).fill('Jon');
await page.getByRole('heading', { name: 'nmleszgear1+mentor1@gmail.com' }).click();
await page.getByRole('heading', { name: 'jonathan.cost+mentor1@' }).click();
await page.getByRole('heading', { name: 'Jonathan Calvin Saintilus' }).click();
await page.getByRole('heading', { name: 'jonathan.cost+admintester1@' }).click();
await page.getByRole('heading', { name: 'Mentors (4)' }).click();
await page.locator('.MuiInputBase-root').click();
await page.getByRole('textbox', { name: 'Search mentors by name, email' }).fill('');await page.getByRole('textbox', { name: 'Search mentors by name, email' }).fill('roojzk+mentor1@gmail.com');
await page.getByRole('paragraph').filter({ hasText: 'roojzk+mentor1@gmail.com' }).click();
await page.getByRole('heading', { name: 'Mentors (1)' }).click();
await page.getByRole('textbox', { name: 'Search mentors by name, email' }).click();
await page.getByRole('textbox', { name: 'Search mentors by name, email' }).fill('NoSuchMentor');
await page.getByRole('heading', { name: 'No mentors found' }).click();
await page.getByRole('heading', { name: 'Mentors (0)' }).click();
});